### ISSUE TITLE
Error:database backend does not accept 0 as default value 

### ISSUE THREAD

**Issue by shirishamuthineni** [3Peers/FusionIIIT#72]
![screenshot 18](https://user-images.githubusercontent.com/31398849/32205512-a701bbac-be15-11e7-8cf3-fade25df357d.png)

**Comment by pranjulps3** [comment]
can you show the model which generated the error.

**Comment by Samy-33** [comment]
@shirishamuthineni , I hope the issue is resolved. Can you confirm?

**Comment by shirishamuthineni** [comment]
No , the issue is not resolved . It was not connecting to database in my
lap top.So I took my friends lap top for my project work.



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality&>

**Comment by Samy-33** [comment]
If you could upload more images of your code, or just put a link to the code, which is giving the error.
